name: Jongpil Lee
description:  Personal Blog dealing with Music and Deep Learning
meta_description: "jongpil lee music information retrieval deep learning blog"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'https://jongpillee.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://jongpillee.github.io/'
author:         'Jongpil Lee'

