name: Jongpil Lee
description:  Music and Deep Learning Blog
meta_description: 'Jongpil Lee Blog: Music Information Retrieval, Deep Learning'

markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'https://jongpillee.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://jongpillee.github.io/'
author:         'Jongpil Lee'

# personal contacts
github_username: 'jongpillee'
gmail_username: 'jongpillee.brian'

disqus: jongpilleeblog

plugins_dir: [jekyll-youtube]
 # This will require each of these gems automatically.