title: Jongpil Lee
description: Jongpil Lee  

url: https://jongpillee.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 3

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: jongpillee
   #twitter: brianmaierjr
   #facebook: brianmaierjr
   email: jongpillee.brian@gmail.com

google_analytics: #"UA-58263416-1"
